/* This file was generated by SableCC (http://www.sablecc.org/). */

package quinas.node;

import quinas.analysis.*;

@SuppressWarnings("nls")
public final class TBinario extends Token
{
    public TBinario(String text)
    {
        setText(text);
    }

    public TBinario(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBinario(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBinario(this);
    }
}
