/* This file was generated by SableCC (http://www.sablecc.org/). */

package quinas.node;

import quinas.analysis.*;

@SuppressWarnings("nls")
public final class TIdConst extends Token
{
    public TIdConst(String text)
    {
        setText(text);
    }

    public TIdConst(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIdConst(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIdConst(this);
    }
}
