/* This file was generated by SableCC (http://www.sablecc.org/). */

package quinas.node;

import quinas.analysis.*;

@SuppressWarnings("nls")
public final class TNumeralInt extends Token
{
    public TNumeralInt(String text)
    {
        setText(text);
    }

    public TNumeralInt(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNumeralInt(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNumeralInt(this);
    }
}
