/* This file was generated by SableCC (http://www.sablecc.org/). */

package quinas.node;

import quinas.analysis.*;

@SuppressWarnings("nls")
public final class TPotencia extends Token
{
    public TPotencia()
    {
        super.setText("´");
    }

    public TPotencia(int line, int pos)
    {
        super.setText("´");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPotencia(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPotencia(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPotencia text.");
    }
}
