/* This file was generated by SableCC (http://www.sablecc.org/). */

package quinas.node;

import quinas.analysis.*;

@SuppressWarnings("nls")
public final class TSustenido extends Token
{
    public TSustenido()
    {
        super.setText("#");
    }

    public TSustenido(int line, int pos)
    {
        super.setText("#");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSustenido(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSustenido(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSustenido text.");
    }
}
