/* This file was generated by SableCC (http://www.sablecc.org/). */

package quinas.analysis;

import quinas.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTNumeralInt(TNumeralInt node);
    void caseTIdConst(TIdConst node);
    void caseTIdFuncao(TIdFuncao node);
    void caseTId(TId node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTResto(TResto node);
    void caseTDivInt(TDivInt node);
    void caseTPotencia(TPotencia node);
    void caseTDecimal(TDecimal node);
    void caseTInteiro(TInteiro node);
    void caseTBinario(TBinario node);
    void caseTBooleano(TBooleano node);
    void caseTMaior(TMaior node);
    void caseTMenor(TMenor node);
    void caseTIgual(TIgual node);
    void caseTColEsq(TColEsq node);
    void caseTColDir(TColDir node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTAnd(TAnd node);
    void caseTNot(TNot node);
    void caseTOr(TOr node);
    void caseTMarcador(TMarcador node);
    void caseTGuarda(TGuarda node);
    void caseTSustenido(TSustenido node);
    void caseTPipe(TPipe node);
    void caseTIgualSimples(TIgualSimples node);
    void caseTVazio(TVazio node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
